### PR TITLE
test case that shows why the current implementation is wrong from an …

### PR DESCRIPTION
**Pull request by koeninger**
…end-user perspective

### CODE REVIEW

**Comment by zsxwing** [comment]
@tdas has some ideas about supporting topic deletions, so I'm going to merge your test into my branch and @tdas will continue to work on it. Thanks a lot!

**Comment by koeninger** [comment]
@tdas Can you please publicly discuss those design ideas on the Jira or the main PR?

So far the ideas I had come up with were

- use time indexing for list of topicpartitions as an alternative to kafka offsets
- add kafka broker time to the Offset, use it as a tiebreaker
- add driver client time to the Offset, use it as a tiebreaker
- remove the methods from Offset, and change the contract for Source.getOffset such that it only returns Some if there is new data.  This is basically an implicit time ordering maintained by the execution.

All of those ideas are time-based, which I think is less than ideal.

**Comment by tdas** [comment]
@koeninger yeah, i am trying to figure out all the options and write up something to so that we are clear on the pros and cons of each approach. At a high level, they match the ones you suggested. Though I am trying to tease out what needs to be done if deletion is to supported, and what needs to be done deletion+recreation of same topic needs to be supported.

**Comment by tdas** [comment]
Also, at a high level I think that supporting deletion of topics does not require timestamps, its supporting deletion+recreation of the same topic would require more disambiguating information like timestamps. Here are a few questions, 

- Just to confirm, there are no unique guid kind of thing for topics in Kafka? 

- When a topic is deleted and recreated, what happens to the offsets? Does the recreated topic's offset start from 0? Or does it start from where the previous topic left off?

**Pull request merged**
